AWSTemplateFormatVersion: "2010-09-09"

Resources:

  ContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ecs-example-repo

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ecs-example-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ecs-example-task-definition-family
      Cpu: 1 vCPU
      Memory: 2 GB
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref TaskExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Image: !Join [ ":", [ !GetAtt ContainerRepository.RepositoryUri, "latest" ] ]
          Name: ecs-example-container
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - FARGATE

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ecs-example-logs

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-example-task-role
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
  
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-example-task-execution-role
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        
Outputs:
  RepositoryUri:
    Description: Docker image repository uri
    Value: !GetAtt ContainerRepository.RepositoryUri
